#!/bin/sh
xrdb ~/.Xresources
(sleep 10; xmodmap ~/.Xmodmap) &

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

xss-lock --transfer-sleep-lock -- i3lock --nofork -e -c 000000 &
dex -ae dwm &
picom &
flameshot &
~/.fehbg
# ~/.localfixes

(sleep 10; systemctl start --user mpdscribble.service) &

tmux new-session -d -s main
tmux new-session -d -s irc mosh pi tmux a
tmux new-session -d -s music ncmpcpp
tmux new-session -d -s notes nvim -c "cd ~/Notes" -c "e landing.txt"

urxvt -name term8 -e tmux attach-session -t notes &
urxvt -name term9 -e tmux attach-session -t music &
urxvt -name term9 -e tmux attach-session -t irc   &

xbindkeys
exec /hdd/builds/dwm/dwm
